import {
  LeagueEnum,
  MatchResolveTypeEnum,
  ScoringTypeEnum,
  PeriodTypeEnum,
  SportEnum,
} from "@/utils/overtime/enums/sport";
import { LeagueInfo } from "@/utils/overtime/types/sports";

//TODO: Might be some shit to do with the images here

export const LeagueMap: Record<LeagueEnum, LeagueInfo> = {
  [LeagueEnum.NCAAF]: {
    sport: SportEnum.FOOTBALL,
    id: LeagueEnum.NCAAF,
    label: "NCAA Football",
    logo: `/logos/leagueLogos/ncaa.webp`,
    logoClass: "icon-homepage league--ncaa",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 202,
    hidden: false,
  },
  [LeagueEnum.NFL]: {
    sport: SportEnum.FOOTBALL,
    id: LeagueEnum.NFL,
    label: "NFL",
    logo: `/logos/leagueLogos/nfl.webp`,
    logoClass: "icon-homepage league--nfl",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 201,
    hidden: false,
  },
  [LeagueEnum.MLB]: {
    sport: SportEnum.BASEBALL,
    id: LeagueEnum.MLB,
    label: "MLB",
    logo: `/logos/leagueLogos/mlb.webp`,
    logoClass: "icon-homepage league--mlb",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.INNING,
    isDrawAvailable: true,
    priority: 401,
    hidden: false,
  },
  [LeagueEnum.NBA]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.NBA,
    label: "NBA",
    logo: `/logos/leagueLogos/nba.webp`,
    logoClass: "icon-homepage league--nba",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 301,
    hidden: false,
  },
  [LeagueEnum.NCAAB]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.NCAAB,
    label: "NCAA Basketball",
    logoClass: "icon-homepage league--ncaa",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 302,
    hidden: false,
  },
  [LeagueEnum.NHL]: {
    sport: SportEnum.HOCKEY,
    id: LeagueEnum.NHL,
    label: "NHL",
    logo: `/logos/leagueLogos/nhl.webp`,
    logoClass: "icon-homepage league--nhl",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.PERIOD,
    isDrawAvailable: false,
    priority: 501,
    hidden: false,
  },
  [LeagueEnum.UFC]: {
    sport: SportEnum.FIGHTING,
    id: LeagueEnum.UFC,
    label: "UFC",
    logo: "/logos/leagueLogos/ufc.webp",
    logoClass: "icon-homepage league--ufc",
    scoringType: ScoringTypeEnum.ROUNDS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.ROUND,
    isDrawAvailable: false,
    priority: 601,
    hidden: false,
  },
  [LeagueEnum.WNBA]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.WNBA,
    label: "WNBA",
    logoClass: "icon-homepage league--wnba",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 304,
    hidden: false,
  },
  [LeagueEnum.MLS]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.MLS,
    label: "MLS",
    logo: `/logos/leagueLogos/mls.webp`,
    logoClass: "icon-homepage league--mls",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 140,
    hidden: false,
  },
  [LeagueEnum.EPL]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.EPL,
    label: "EPL",
    logo: `/logos/leagueLogos/EPL.webp`,
    logoClass: "icon-homepage league--epl",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 120,
    hidden: false,
  },
  [LeagueEnum.LIGUE_ONE]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.LIGUE_ONE,
    label: "Ligue 1",
    logo: `/logos/leagueLogos/Ligue1.webp`,
    logoClass: "icon-homepage league--ligue1",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 124,
    hidden: false,
  },

  [LeagueEnum.BUNDESLIGA]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.BUNDESLIGA,
    label: "Bundesliga",
    logo: "/logos/leagueLogos/bundesliga.webp",
    logoClass: "icon-homepage league--bundesliga",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 123,
    hidden: false,
  },
  [LeagueEnum.LA_LIGA]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.LA_LIGA,
    label: "La Liga",
    logo: `/logos/leagueLogos/LaLiga.webp`,
    logoClass: "icon-homepage league--la-liga",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 121,
    hidden: false,
  },
  [LeagueEnum.SERIE_A]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.SERIE_A,
    label: "Serie A",
    logo: `/logos/leagueLogos/seriea.webp`,
    logoClass: "icon-homepage league--serie-a",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 122,
    hidden: false,
  },
  [LeagueEnum.UEFA_CL]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_CL,
    label: "UEFA Champions League",
    logo: `/logos/leagueLogos/ucl-white.webp`,
    logoClass: "icon-homepage league--ucl",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 103,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.UEFA_EL]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_EL,
    label: "UEFA Europa League",
    logoClass: "icon-homepage league--uel",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 104,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.FIFA_WC]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.FIFA_WC,
    label: "FIFA World Cup",
    logoClass: "icon-homepage league--fifa-world-cup",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 100,
    hidden: true,
    tooltipKey: "common.fifa-tooltip",
  },
  [LeagueEnum.J1_LEAGUE]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.J1_LEAGUE,
    label: "J1 League",
    logoClass: "icon-homepage league--j1",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 144,
    hidden: false,
  },
  [LeagueEnum.IPL]: {
    sport: SportEnum.CRICKET,
    id: LeagueEnum.IPL,
    label: "Indian Premier League",
    logoClass: "icon-homepage league--ipl",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.INNING,
    isDrawAvailable: false,
    priority: 901,
    hidden: false,
  },
  [LeagueEnum.T20_BLAST]: {
    sport: SportEnum.CRICKET,
    id: LeagueEnum.T20_BLAST,
    label: "T20 Blast",
    logoClass: "icon-homepage league--t20",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.INNING,
    isDrawAvailable: false,
    priority: 902,
    hidden: false,
  },
  [LeagueEnum.IIHF_WORLD_CHAMPIONSHIP]: {
    sport: SportEnum.HOCKEY,
    id: LeagueEnum.IIHF_WORLD_CHAMPIONSHIP,
    label: "IIHF World Championship",
    logoClass: "icon-homepage league--iihf",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.PERIOD,
    isDrawAvailable: true,
    priority: 502,
    hidden: false,
    tooltipKey: "common.iihf-tooltip",
  },
  [LeagueEnum.COPA_AMERICA]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.COPA_AMERICA,
    label: "Copa America 2024",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 102,
    hidden: true,
  },
  [LeagueEnum.COPA_LIBERTADORES]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.COPA_LIBERTADORES,
    label: "Copa Libertadores",
    logoClass: "icon-homepage league--copa-libertadores",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 107,
    hidden: false,
  },
  [LeagueEnum.UEFA_EURO]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_EURO,
    label: "UEFA EURO 2024",
    logoClass: "icon-homepage league--uefa",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 101,
    hidden: true,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.EREDIVISIE]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.EREDIVISIE,
    label: "Eredivisie",
    logoClass: "icon-homepage league--eredivisie",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 141,
    hidden: false,
  },
  [LeagueEnum.PRIMEIRA_LIGA]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.PRIMEIRA_LIGA,
    label: "Primeira Liga",
    logoClass: "icon-homepage league--portugal",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 142,
    hidden: false,
  },
  [LeagueEnum.SUMMER_OLYMPICS_SOCCER_WOMEN]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.SUMMER_OLYMPICS_SOCCER_WOMEN,
    label: "Olympic Games Soccer Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 102,
    hidden: true,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.SUMMER_OLYMPICS_SOCCER]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.SUMMER_OLYMPICS_SOCCER,
    logoClass: "icon-homepage league--paris2024",
    label: "Olympic Games Soccer",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 102,
    hidden: true,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.FIFA_WC_WOMEN]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.FIFA_WC_WOMEN,
    label: "FIFA World Cup Women",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 112,
    hidden: true,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.ENGLAND_CUP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.ENGLAND_CUP,
    label: "FA Cup",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 130,
    hidden: false,
  },
  [LeagueEnum.FRANCE_CUP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.FRANCE_CUP,
    label: "Coupe de France",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 134,
    hidden: false,
  },
  [LeagueEnum.SPAIN_CUP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.SPAIN_CUP,
    label: "Copa del Rey",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 131,
    hidden: false,
  },
  [LeagueEnum.ITALY_CUP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.ITALY_CUP,
    label: "Coppa Italia",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 132,
    hidden: false,
  },
  [LeagueEnum.TENNIS_GS]: {
    sport: SportEnum.TENNIS,
    id: LeagueEnum.TENNIS_GS,
    label: "Grand Slam",
    logo: `/logos/Tennis/atp.webp`,
    logoClass: "icon-homepage league--atp",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 701,
    hidden: false,
    tooltipKey: "common.tennis-tooltip",
  },
  [LeagueEnum.TENNIS_MASTERS]: {
    sport: SportEnum.TENNIS,
    id: LeagueEnum.TENNIS_MASTERS,
    label: "ATP Events",
    logo: `/logos/Tennis/atp.webp`,
    logoClass: "icon-homepage league--atp",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 702,
    hidden: false,
    tooltipKey: "common.tennis-tooltip",
  },
  [LeagueEnum.SUMMER_OLYMPICS_TENNIS]: {
    sport: SportEnum.TENNIS,
    id: LeagueEnum.SUMMER_OLYMPICS_TENNIS,
    label: "Olympic Games Tennis",
    logo: `/logos/Tennis/atp.webp`,
    logoClass: "icon-homepage league--atp",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 700,
    hidden: true,
    tooltipKey: "common.tennis-tooltip",
  },
  [LeagueEnum.GERMANY_CUP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.GERMANY_CUP,
    label: "DFB Pokal",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 133,
    hidden: false,
  },
  [LeagueEnum.LIGA_MX]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.LIGA_MX,
    label: "Liga MX",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 150,
    hidden: false,
  },
  [LeagueEnum.BRAZIL_1]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.BRAZIL_1,
    label: "Serie A",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 143,
    hidden: false,
  },
  [LeagueEnum.UEFA_EURO_U21]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_EURO_U21,
    label: "UEFA EURO U21",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 111,
    hidden: true,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.FIFA_WORLD_CUP_U20]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.FIFA_WORLD_CUP_U20,
    label: "FIFA World Cup U20",
    logoClass: "icon-homepage league--fifa-world-cup-u20",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 110,
    hidden: true,
    tooltipKey: "common.fifa-tooltip",
  },
  [LeagueEnum.SUMMER_OLYMPICS_HANDBALL_WOMEN]: {
    sport: SportEnum.HANDBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_HANDBALL_WOMEN,
    label: "Olympic Games Handball Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 1402,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_HANDBALL]: {
    sport: SportEnum.HANDBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_HANDBALL,
    label: "Olympic Games Handball",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 1401,
    hidden: true,
  },
  [LeagueEnum.EUROLEAGUE]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.EUROLEAGUE,
    label: "Euroleague",
    logoClass: "icon-homepage league--euroleague",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 303,
    hidden: false,
  },
  [LeagueEnum.SUMMER_OLYMPICS_BASKETBALL]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_BASKETBALL,
    label: "Olympic Games Basketball",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 305,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_WOMEN]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_WOMEN,
    label: "Olympic Games Basketball Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 305,
    hidden: true,
  },
  [LeagueEnum.FIBA_WORLD_CUP]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.FIBA_WORLD_CUP,
    label: "FIBA World Cup",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 300,
    hidden: true,
  },
  [LeagueEnum.FORMULA1]: {
    sport: SportEnum.MOTOSPORT,
    id: LeagueEnum.FORMULA1,
    label: "Formula 1",
    logo: "/logos/leagueLogos/f1.webp",
    logoClass: "icon-homepage league--f1",
    scoringType: ScoringTypeEnum.EMPTY,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.EMPTY,
    isDrawAvailable: false,
    priority: 1001,
    hidden: false,
  },
  [LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN]: {
    sport: SportEnum.VOLLEYBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN,
    label: "Olympic Games Beach Voleyball Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 1304,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL]: {
    sport: SportEnum.VOLLEYBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL,
    label: "Olympic Games Beach Voleyball",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 1303,
    hidden: true,
  },
  [LeagueEnum.MOTOGP]: {
    sport: SportEnum.MOTOSPORT,
    id: LeagueEnum.MOTOGP,
    label: "MotoGP",
    logo: `/logos/leagueLogos/motogp.webp`,
    logoClass: "icon-homepage league--motogp",
    scoringType: ScoringTypeEnum.EMPTY,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.EMPTY,
    isDrawAvailable: false,
    priority: 1002,
    hidden: true,
  },
  [LeagueEnum.SAUDI_PROFESSIONAL_LEAGUE]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.SAUDI_PROFESSIONAL_LEAGUE,
    label: "Saudi Professional League",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 145,
    hidden: false,
  },
  [LeagueEnum.SUMMER_OLYMPICS_WATERPOLO]: {
    sport: SportEnum.WATERPOLO,
    id: LeagueEnum.SUMMER_OLYMPICS_WATERPOLO,
    label: "Olympic Games Water Polo",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: true,
    priority: 1501,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL_WOMEN]: {
    sport: SportEnum.VOLLEYBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL_WOMEN,
    label: "Olympic Games Voleyball Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 1302,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL]: {
    sport: SportEnum.VOLLEYBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL,
    label: "Olympic Games Voleyball",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 1301,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_TABLE_TENNIS]: {
    sport: SportEnum.TABLE_TENNIS,
    id: LeagueEnum.SUMMER_OLYMPICS_TABLE_TENNIS,
    label: "Olympic Games Table Tennis",
    scoringType: ScoringTypeEnum.SETS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.SET,
    isDrawAvailable: false,
    priority: 1601,
    hidden: true,
  },
  [LeagueEnum.BOXING]: {
    sport: SportEnum.FIGHTING,
    id: LeagueEnum.BOXING,
    label: "Boxing",
    logoClass: "icon-homepage league--boxing",
    scoringType: ScoringTypeEnum.ROUNDS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.ROUND,
    isDrawAvailable: false,
    priority: 602,
    hidden: false,
  },
  [LeagueEnum.SUMMER_OLYMPICS_RUGBY]: {
    sport: SportEnum.RUGBY,
    id: LeagueEnum.SUMMER_OLYMPICS_RUGBY,
    label: "Olympic Games Rugby",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 1201,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_RUGBY_WOMEN]: {
    sport: SportEnum.RUGBY,
    id: LeagueEnum.SUMMER_OLYMPICS_RUGBY_WOMEN,
    label: "Olympic Games Rugby Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 1202,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_HOCKEY_WOMEN]: {
    sport: SportEnum.HOCKEY,
    id: LeagueEnum.SUMMER_OLYMPICS_HOCKEY_WOMEN,
    label: "Olympic Games Hockey Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.PERIOD,
    isDrawAvailable: true,
    priority: 504,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_HOCKEY]: {
    sport: SportEnum.HOCKEY,
    id: LeagueEnum.SUMMER_OLYMPICS_HOCKEY,
    label: "Olympic Games Hockey",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.PERIOD,
    isDrawAvailable: true,
    priority: 503,
    hidden: true,
  },
  [LeagueEnum.UEFA_NATIONS_LEAGUE]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_NATIONS_LEAGUE,
    label: "UEFA Nations League",
    logoClass: "icon-homepage league--uefa-nations",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 106,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.CONCACAF_NATIONS_LEAGUE]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.CONCACAF_NATIONS_LEAGUE,
    label: "CONCACAF Nations League",
    logoClass: "icon-homepage league--concacaf-nations",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 108,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.CSGO]: {
    sport: SportEnum.ESPORTS,
    id: LeagueEnum.CSGO,
    label: "CS2",
    logoClass: "icon-homepage league--csgo",
    scoringType: ScoringTypeEnum.ROUNDS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.ROUND,
    isDrawAvailable: false,
    priority: 801,
    hidden: false,
  },
  [LeagueEnum.DOTA2]: {
    sport: SportEnum.ESPORTS,
    id: LeagueEnum.DOTA2,
    label: "DOTA 2",
    logoClass: "icon-homepage league--dota2",
    scoringType: ScoringTypeEnum.ROUNDS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.ROUND,
    isDrawAvailable: false,
    priority: 802,
    hidden: false,
  },
  [LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3,
    label: "Olympic Games Basketball 3x3",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 306,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN,
    label: "Olympic Games Basketball 3x3 Women",
    logoClass: "icon-homepage league--paris2024",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 306,
    hidden: true,
  },
  [LeagueEnum.SUMMER_OLYMPICS_QUALIFICATION]: {
    sport: SportEnum.BASKETBALL,
    id: LeagueEnum.SUMMER_OLYMPICS_QUALIFICATION,
    label: "Summer Olympics Qualification",
    scoringType: ScoringTypeEnum.POINTS,
    matchResolveType: MatchResolveTypeEnum.OVERTIME,
    periodType: PeriodTypeEnum.QUARTER,
    isDrawAvailable: false,
    priority: 305,
    hidden: true,
  },
  [LeagueEnum.LOL]: {
    sport: SportEnum.ESPORTS,
    id: LeagueEnum.LOL,
    label: "LOL",
    logoClass: "icon-homepage league--lol",
    scoringType: ScoringTypeEnum.ROUNDS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.ROUND,
    isDrawAvailable: false,
    priority: 803,
    hidden: false,
  },
  [LeagueEnum.CONMEBOL_WC_QUALIFICATIONS]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.CONMEBOL_WC_QUALIFICATIONS,
    label: "CONMEBOL WC Qualification",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 109,
    hidden: false,
  },
  [LeagueEnum.UEFA_CONFERENCE_LEAGUE]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_CONFERENCE_LEAGUE,
    label: "UEFA Conference League",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 105,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.NON_TITLE_BOXING]: {
    sport: SportEnum.FIGHTING,
    id: LeagueEnum.NON_TITLE_BOXING,
    label: "Boxing",
    logoClass: "icon-homepage league--boxing",
    scoringType: ScoringTypeEnum.ROUNDS,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.ROUND,
    isDrawAvailable: false,
    priority: 603,
    hidden: false,
  },
  [LeagueEnum.UEFA_CHAMPIONS_LEAGUE_QUALIFICATION]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_CHAMPIONS_LEAGUE_QUALIFICATION,
    label: "UEFA Champions League Qualification",
    logo: `/logos/leagueLogos/ucl-white.webp`,
    logoClass: "icon-homepage league--ucl",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 103,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.UEFA_EUROPA_LEAGUE_QUALIFICATION]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_EUROPA_LEAGUE_QUALIFICATION,
    label: "UEFA Europa League Qualification",
    logoClass: "icon-homepage league--uel",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 104,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.UEFA_CONFERENCE_LEAGUE_QUALIFICATION]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_CONFERENCE_LEAGUE_QUALIFICATION,
    label: "UEFA Conference League Qualification",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 105,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.US_ELECTION]: {
    sport: SportEnum.POLITICS,
    id: LeagueEnum.US_ELECTION,
    label: "US Election 2024",
    scoringType: ScoringTypeEnum.EMPTY,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.EMPTY,
    isDrawAvailable: false,
    priority: 1701,
    hidden: false,
    tooltipKey: "common.election-tooltip",
  },
  [LeagueEnum.UEFA_SUPER_CUP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.UEFA_SUPER_CUP,
    label: "UEFA Super Cup",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 102,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.BRAZIL_CUP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.BRAZIL_CUP,
    label: "Copa do Brasil",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 135,
    hidden: false,
    tooltipKey: "common.football-tooltip",
  },
  [LeagueEnum.ENGLAND_CHAMPIONSHIP]: {
    sport: SportEnum.SOCCER,
    id: LeagueEnum.ENGLAND_CHAMPIONSHIP,
    label: "EFL Championship",
    scoringType: ScoringTypeEnum.GOALS,
    matchResolveType: MatchResolveTypeEnum.REGULAR,
    periodType: PeriodTypeEnum.HALF,
    isDrawAvailable: true,
    priority: 125,
    hidden: false,
  },
  [LeagueEnum.GOLF_H2H]: {
    sport: SportEnum.GOLF,
    id: LeagueEnum.GOLF_H2H,
    label: "Golf head-to-head",
    logoClass: "icon-homepage league--pga",
    scoringType: ScoringTypeEnum.EMPTY,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.EMPTY,
    isDrawAvailable: false,
    priority: 1101,
    hidden: false,
  },
  [LeagueEnum.GOLF_WINNER]: {
    sport: SportEnum.GOLF,
    id: LeagueEnum.GOLF_WINNER,
    label: "Golf Tournament Winner",
    logoClass: "icon-homepage league--pga",
    scoringType: ScoringTypeEnum.EMPTY,
    matchResolveType: MatchResolveTypeEnum.EMPTY,
    periodType: PeriodTypeEnum.EMPTY,
    isDrawAvailable: false,
    priority: 1102,
    hidden: false,
  },
};

export const BOXING_LEAGUES = [LeagueEnum.BOXING, LeagueEnum.NON_TITLE_BOXING];

export const INTERNATIONAL_LEAGUES = [
  LeagueEnum.FIFA_WC,
  LeagueEnum.IIHF_WORLD_CHAMPIONSHIP,
  LeagueEnum.UEFA_EURO,
  LeagueEnum.FIFA_WC_WOMEN,
  LeagueEnum.UEFA_EURO_U21,
  LeagueEnum.FIFA_WORLD_CUP_U20,
  LeagueEnum.FIBA_WORLD_CUP,
  LeagueEnum.UEFA_NATIONS_LEAGUE,
  LeagueEnum.CONCACAF_NATIONS_LEAGUE,
  LeagueEnum.CONMEBOL_WC_QUALIFICATIONS,
  LeagueEnum.COPA_AMERICA,
  LeagueEnum.SUMMER_OLYMPICS_QUALIFICATION,
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL,
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3,
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_SOCCER,
  LeagueEnum.SUMMER_OLYMPICS_SOCCER_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_RUGBY,
  LeagueEnum.SUMMER_OLYMPICS_RUGBY_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL,
  LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_HANDBALL,
  LeagueEnum.SUMMER_OLYMPICS_HANDBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_WATERPOLO,
  LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL,
  LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_HOCKEY,
  LeagueEnum.SUMMER_OLYMPICS_HOCKEY_WOMEN,
];

export const OLYMPIC_LEAGUES = [
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL,
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3,
  LeagueEnum.SUMMER_OLYMPICS_BASKETBALL_3X3_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_SOCCER,
  LeagueEnum.SUMMER_OLYMPICS_SOCCER_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_RUGBY,
  LeagueEnum.SUMMER_OLYMPICS_RUGBY_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL,
  LeagueEnum.SUMMER_OLYMPICS_VOLEYBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_HANDBALL,
  LeagueEnum.SUMMER_OLYMPICS_HANDBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_WATERPOLO,
  LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL,
  LeagueEnum.SUMMER_OLYMPICS_BEACH_VOLEYBALL_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_HOCKEY,
  LeagueEnum.SUMMER_OLYMPICS_HOCKEY_WOMEN,
  LeagueEnum.SUMMER_OLYMPICS_TENNIS,
  LeagueEnum.SUMMER_OLYMPICS_TABLE_TENNIS,
];

export const PLAYER_PROPS_COMBINING_ENABLED_LEAGUES = [LeagueEnum.NBA];
